### ISSUE TITLE
Missing IE support?

### ISSUE THREAD

**Issue by pwFoo** [chrisnager/ungrid#11]
The demo doesn't work with IE <=10? Is it correct? No support for older IE (8-10) versions?

**Comment by DWboutin** [comment]
seriously!? https://developer.mozilla.org/fr/docs/Web/CSS/table-layout

**Comment by pwFoo** [comment]
Don't know why... Tested sucessful with native edge, ie11, Chrome.
Virtual Win7 / XP with IE8 and IE-Tester some Tests failed...
I'll try it again. Maybe a local problem with VM / IE-Tester, but Tests Werke fine in the past with that test setup...

**Comment by pwFoo** [comment]
I close this issue because it should be caused by my local test environment...?

**Comment by adiv5** [comment]
maybe it doesnot works for Older browsers upto IE 10

**Comment by DWboutin** [comment]
It's a CSS2 feature lol, come on...
