### ISSUE TITLE
Suggestion: Make a React component installable from npmjs

### ISSUE THREAD

**Issue by thevangelist** [chrisnager/ungrid#13]

**Comment by chrisnager** [comment]
@thevangelist I ❤️ React, but I have no plans to make a specific ungrid React component. However, you inspired me to build [an implementation of ungrid using React](http://codepen.io/chrisnager/pen/oYRzPz). I added the React example to the [README](https://github.com/chrisnager/ungrid#helpful-resources) with a reference to the issue you opened. Thanks for your suggestion!

**Comment by thevangelist** [comment]
Awesome! :)
