### ISSUE TITLE
Row inside row

### ISSUE THREAD

**Issue by hariawan** [chrisnager/ungrid#5]
This is how looks like if I put a row inside row.

![](https://cldup.com/aOFofCqnsa.png)

Any solution?

**Comment by hariawan** [comment]
Sorry, just knew that I put `<form>` inside `<row>`, it's supposed to be `<row>` inside `<form>`

**Comment by chrisnager** [comment]
Hey @hariawan! I addressed nested grids in Issue #1. Feel free to take a look and see if [this example](http://codepen.io/chrisnager/pen/EeJqH?editors=110) answers your question. Also, please send me a link to your site that uses ungrid. I'd love to keep a list of live examples that are using ungrid. Thanks!
