### ISSUE TITLE
First column filled with text & second column filled with image problem

### ISSUE THREAD

**Issue by hariawan** [chrisnager/ungrid#9]
How to solve this problem?

I tried to add a paragraph in first column then I want to put an image on second column, but the result is not good, my paragraph on first column at the bottom.

Here is the example http://jsbin.com/jizoratahu/edit?html,output

Any suggestion?

**Comment by chrisnager** [comment]
hey @hariawan, adding `.col { vertical-align: top }` should fix your issue. you can also use `.col { vertical-align: middle }` for vertically centered alignment. :wink:
